name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to Dockerhub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: create docker-compose stack
        run: docker-compose up -d
      - name: check docker containers
        run: docker ps
      - name: change docker image
        run: docker image tag postboard rainerbonilla/postboard:latest
      - name: push image to dockerhub
        run: docker push rainerbonilla/postboard:latest
