name: react CI

on:
  push:
    branches:
      - testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install dependencies
      run: npm install
    - name: Test app
      run: npm run tester
    - name: Build application
      run: npm run build
      env:
        CI: true
